volumes:
  our_house_local_postgres_data: {}
  our_house_local_postgres_data_backups: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: our_house_local_django
    container_name: our_house_local_django
    volumes:
      - /app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8111:8000'
    command: /start
