# Generated by Django 4.2.13 on 2024-05-23 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='appliance_documents/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='appliance_images/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CircuitDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='circuit_diagrams/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaintColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint_code', models.CharField(max_length=100)),
                ('paint_color', models.CharField(max_length=100)),
                ('paint_base', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.room')),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('breaker_size', models.CharField(choices=[('15A', '15A'), ('20A', '20A'), ('30A', '30A'), ('40A', '40A'), ('50A', '50A')], max_length=10)),
                ('gfci', models.BooleanField(default=False)),
                ('afci', models.BooleanField(default=False)),
                ('cafi', models.BooleanField(default=False)),
                ('pole_type', models.CharField(choices=[('single', 'Single Pole'), ('double', 'Double Pole')], max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.room')),
            ],
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('appliance_type', models.CharField(choices=[('gas', 'Gas'), ('electric', 'Electric'), ('induction', 'Induction')], max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('owners_manual', models.FileField(blank=True, null=True, upload_to='owners_manuals/')),
                ('purchase_location', models.CharField(max_length=100)),
                ('registered', models.BooleanField(default=False)),
                ('purchase_date', models.DateField()),
                ('power_demands', models.CharField(max_length=100)),
                ('additional_pdfs', models.ManyToManyField(blank=True, to='info.appliancedocument')),
                ('images', models.ManyToManyField(blank=True, to='info.applianceimage')),
            ],
        ),
    ]
