# Generated by Django 4.2.13 on 2024-05-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_appliance_power_demands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='room',
        ),
        migrations.AddField(
            model_name='circuit',
            name='diagrams',
            field=models.ManyToManyField(blank=True, to='info.circuitdiagram'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='info.room'),
        ),
    ]
