# Generated by Django 4.2.13 on 2024-05-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_circuit_room_circuit_diagrams_circuit_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
