# Generated by Django 4.2.13 on 2024-05-24 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_appliance_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='additional_pdfs',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='images',
        ),
        migrations.AddField(
            model_name='appliancedocument',
            name='appliance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='info.appliance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applianceimage',
            name='appliance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='info.appliance'),
            preserve_default=False,
        ),
    ]
