# Generated by Django 4.2.13 on 2024-05-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_appliance_additional_pdfs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applianceimage',
            name='appliance',
        ),
        migrations.AddField(
            model_name='appliance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appliance_images/'),
        ),
        migrations.DeleteModel(
            name='ApplianceDocument',
        ),
        migrations.DeleteModel(
            name='ApplianceImage',
        ),
    ]
