# Generated by Django 4.2.13 on 2024-05-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_applianceimage_appliance_appliance_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paintcolor',
            name='room',
        ),
        migrations.AddField(
            model_name='paintcolor',
            name='room',
            field=models.ManyToManyField(to='info.room'),
        ),
    ]
